# This workflow checks if the project can be built correctly and runs its unit tests
# This workflow only runs if a Pull Request is (re-)opened and it is not a draft 
# or after a push to develop or the default branch
# For more information about best practices, see:
# https://grandcentrix.atlassian.net/wiki/spaces/TENG/pages/31180230199/GitHub+Actions+Best+Practices

name: Pull Request

on:
  push:
    branches: [ develop, $default-branch ]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
      
jobs:
  cancelPreviousRuns:
    name: Cancel previous runs
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Build and Run tests
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v
      timeout-minutes: 10