# This workflow checks if the project can be built correctly and runs its unit tests and linter
# After the tests have run it prints a report in the logs and uploads a report as workflow artifact
# This workflow only runs if a Pull Request is (re-)opened and it is not a draft 
# or after a push to develop or the default branch
# For more information about best practices, see:
# https://grandcentrix.atlassian.net/wiki/spaces/TENG/pages/31180230199/GitHub+Actions+Best+Practices

name: Pull Request

on:
  push:
    branches: [ develop, $default-branch ]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build all variants
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Cache gradle wrapper and packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Build all variants
        run: ./gradlew assemble
        timeout-minutes: 10

  test:
    name: Run Unit Tests & Lint
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Cache gradle wrapper and packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Compile tests
        run: ./gradlew compileDebugUnitTests
      - name: Run tests
        run: ./gradlew testDebugUnitTest --continue
        timeout-minutes: 10
      - name: Annotate PR with JUnit Report
        uses: mikepenz/action-junit-report@v2.2.0
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run lint
        run: ./gradlew lintDebug
        timeout-minutes: 5
      - name: Annotate PR with Lint Report
        uses: yutailang0119/action-android-lint@v1.0.2
        if: always() # always run even if the previous step fails
        with:
          xml_path: '**/build/reports/lint-results-debug.xml'
      - name: Upload test and lint reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: "**/build/reports/*"
