# This workflow publishes a release build of e.g. a library project 
# to a Maven repository like GitHub Packages using the maven-publish plugin
# It is triggered by the creation of a GitHub release
# Please note that the KeyStore credentials have to be created as secrets in your project
# For more information about how to configure your project to use this, see:
# https://grandcentrix.atlassian.net/wiki/spaces/TENG/pages/31180229044/GitHub+Packages+for+Android+Projects
# For more information about best practices, see:
# https://grandcentrix.atlassian.net/wiki/spaces/TENG/pages/31180230199/GitHub+Actions+Best+Practices

name: Publish Artifact

on:
  release:
    types: [ released ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK 8
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4.0.1
      - name: Build release
        run: ./gradlew assembleRelease
        timeout-minutes: 10
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
