# This workflow checks if the project can be built correctly and runs its unit tests and linter
# After the tests have run it prints a report in the logs and uploads a report as workflow artifact
# This workflow only runs if a Pull Request is (re-)opened and it is not a draft 
# or after a push to develop or the default branch
# For more information about best practices, see:
# https://grandcentrix.atlassian.net/wiki/spaces/TENG/pages/31180230199/GitHub+Actions+Best+Practices

name: Pull Request

on:
  push:
    branches: [ develop, $default-branch ]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build all variants
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK 8
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      - name: Build all variants
        run: ./gradlew assemble
        timeout-minutes: 10

  test:
    name: Run Unit Tests & Lint
    if: github.event_name == 'push' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK 8
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      - name: Compile tests
        run: ./gradlew compileDebugUnitTests
      - name: Run tests
        run: ./gradlew testDebugUnitTest --continue
        timeout-minutes: 10
      - name: Annotate PR with JUnit Report
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4.3.1
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run lint
        run: ./gradlew lintDebug
        timeout-minutes: 5
      - name: Upload test and lint reports
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: reports
          path: "**/build/reports/*"
