# This workflow builds the release variant of the project after a GitHub release was created
# The build artifact is uploaded as release artifact
# For more information about best practices, see:
# https://wiki.gcxi.de/display/TENG/GitHub+Actions%3A+Best+Practices

name: Build Release

on:
  release:
    types: [released]

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache gradle wrapper and packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Build Release
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        timeout-minutes: 10
      - name: Upload build outputs
        uses: actions/upload-artifact@v2
        with:
          name: release-outputs
          path: 'app/build/outputs/'